---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zyrlfinl/api.zyrlent.com
    - /bin/cp -R ./ $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan migrate --force
